/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/test-html`; params?: Router.UnknownInputParams; } | { pathname: `/test`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorldMap/LevelNode`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorldMap/MascotHelper`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorldMap/Level1Map`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Library/BookList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/level1`; params?: Router.UnknownInputParams; } | { pathname: `/level1/literacy/letter-monster`; params?: Router.UnknownInputParams; } | { pathname: `/sticker-book`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/test-html`; params?: Router.UnknownOutputParams; } | { pathname: `/test`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WorldMap/LevelNode`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WorldMap/MascotHelper`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WorldMap/Level1Map`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Library/BookList`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/level1`; params?: Router.UnknownOutputParams; } | { pathname: `/level1/literacy/letter-monster`; params?: Router.UnknownOutputParams; } | { pathname: `/sticker-book`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/test-html${`?${string}` | `#${string}` | ''}` | `/test${`?${string}` | `#${string}` | ''}` | `/../components/WorldMap/LevelNode${`?${string}` | `#${string}` | ''}` | `/../components/WorldMap/MascotHelper${`?${string}` | `#${string}` | ''}` | `/../components/WorldMap/Level1Map${`?${string}` | `#${string}` | ''}` | `/../components/Library/BookList${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/library${`?${string}` | `#${string}` | ''}` | `/library${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/level1${`?${string}` | `#${string}` | ''}` | `/level1/literacy/letter-monster${`?${string}` | `#${string}` | ''}` | `/sticker-book${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/test-html`; params?: Router.UnknownInputParams; } | { pathname: `/test`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorldMap/LevelNode`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorldMap/MascotHelper`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorldMap/Level1Map`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Library/BookList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/level1`; params?: Router.UnknownInputParams; } | { pathname: `/level1/literacy/letter-monster`; params?: Router.UnknownInputParams; } | { pathname: `/sticker-book`; params?: Router.UnknownInputParams; };
    }
  }
}
